begin;

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  username text,
  first_name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint users_telegram_id_key unique (telegram_id),
  constraint users_telegram_id_positive check (telegram_id > 0),
  constraint users_first_name_not_blank check (length(btrim(first_name)) > 0)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  user_message text not null,
  ai_response text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint messages_telegram_id_fkey
    foreign key (telegram_id)
    references public.users (telegram_id)
    on delete cascade,
  constraint messages_user_message_not_blank check (length(btrim(user_message)) > 0),
  constraint messages_ai_response_not_blank check (length(btrim(ai_response)) > 0)
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  memory text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint memories_telegram_id_fkey
    foreign key (telegram_id)
    references public.users (telegram_id)
    on delete cascade,
  constraint memories_memory_not_blank check (length(btrim(memory)) > 0)
);

create index if not exists users_created_at_idx
  on public.users (created_at desc);

create index if not exists users_username_idx
  on public.users (username)
  where username is not null;

create index if not exists messages_telegram_id_created_at_idx
  on public.messages (telegram_id, created_at desc);

create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

create index if not exists memories_telegram_id_created_at_idx
  on public.memories (telegram_id, created_at desc);

create index if not exists memories_created_at_idx
  on public.memories (created_at desc);

alter table public.users enable row level security;
alter table public.messages enable row level security;
alter table public.memories enable row level security;

drop policy if exists users_backend_access on public.users;
create policy users_backend_access
  on public.users
  for all
  to anon, authenticated, service_role
  using (true)
  with check (true);

drop policy if exists messages_backend_access on public.messages;
create policy messages_backend_access
  on public.messages
  for all
  to anon, authenticated, service_role
  using (true)
  with check (true);

drop policy if exists memories_backend_access on public.memories;
create policy memories_backend_access
  on public.memories
  for all
  to anon, authenticated, service_role
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.users to anon, authenticated, service_role;
grant select, insert, update, delete on public.messages to anon, authenticated, service_role;
grant select, insert, update, delete on public.memories to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

create or replace function public.upsert_telegram_user(
  p_telegram_id bigint,
  p_username text default null,
  p_first_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
begin
  insert into public.users (telegram_id, username, first_name)
  values (
    p_telegram_id,
    nullif(btrim(coalesce(p_username, '')), ''),
    coalesce(nullif(btrim(coalesce(p_first_name, '')), ''), 'there')
  )
  on conflict (telegram_id)
  do update
    set username = excluded.username,
        first_name = excluded.first_name
  returning * into v_user;

  return to_jsonb(v_user);
end;
$$;

create or replace function public.remember_fact(
  p_telegram_id bigint,
  p_memory text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_memory public.memories;
begin
  insert into public.memories (telegram_id, memory)
  values (
    p_telegram_id,
    btrim(p_memory)
  )
  returning * into v_memory;

  return to_jsonb(v_memory);
end;
$$;

create or replace function public.save_conversation(
  p_telegram_id bigint,
  p_user_message text,
  p_ai_response text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_message public.messages;
begin
  insert into public.messages (telegram_id, user_message, ai_response)
  values (
    p_telegram_id,
    btrim(p_user_message),
    btrim(p_ai_response)
  )
  returning * into v_message;

  return to_jsonb(v_message);
end;
$$;

create or replace function public.get_user_context(
  p_telegram_id bigint,
  p_message_limit integer default 12,
  p_memory_limit integer default 10
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with user_row as (
    select to_jsonb(u) as data
    from public.users u
    where u.telegram_id = p_telegram_id
    limit 1
  ),
  history_rows as (
    select jsonb_agg(
      jsonb_build_object(
        'id', m.id,
        'user_message', m.user_message,
        'ai_response', m.ai_response,
        'created_at', m.created_at
      )
      order by m.created_at desc
    ) as data
    from (
      select id, user_message, ai_response, created_at
      from public.messages
      where telegram_id = p_telegram_id
      order by created_at desc
      limit greatest(coalesce(p_message_limit, 12), 1)
    ) m
  ),
  memory_rows as (
    select jsonb_agg(
      jsonb_build_object(
        'id', m.id,
        'memory', m.memory,
        'created_at', m.created_at
      )
      order by m.created_at desc
    ) as data
    from (
      select id, memory, created_at
      from public.memories
      where telegram_id = p_telegram_id
      order by created_at desc
      limit greatest(coalesce(p_memory_limit, 10), 1)
    ) m
  )
  select jsonb_build_object(
    'user', coalesce((select data from user_row), '{}'::jsonb),
    'history', coalesce((select data from history_rows), '[]'::jsonb),
    'memories', coalesce((select data from memory_rows), '[]'::jsonb)
  );
$$;

grant execute on function public.upsert_telegram_user(bigint, text, text) to anon, authenticated, service_role;
grant execute on function public.remember_fact(bigint, text) to anon, authenticated, service_role;
grant execute on function public.save_conversation(bigint, text, text) to anon, authenticated, service_role;
grant execute on function public.get_user_context(bigint, integer, integer) to anon, authenticated, service_role;

comment on table public.users is 'Telegram users tracked by the assistant.';
comment on table public.messages is 'Conversation history stored per Telegram user.';
comment on table public.memories is 'Long-term user facts remembered by the assistant.';

commit;

