begin;

create extension if not exists pgcrypto;

-- One row represents one bot session, from /start until /endchat.
create table if not exists public.bot_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null,
  chat_id bigint,
  username text,
  first_name text,
  last_name text,
  status text not null default 'active'
    check (status in ('active', 'ended')),
  current_feature text,
  preferences jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  ended_at timestamptz
);

-- A user can have only one open session at a time.
create unique index if not exists bot_sessions_one_active_per_user_idx
  on public.bot_sessions (user_id)
  where status = 'active';

create index if not exists bot_sessions_user_started_idx
  on public.bot_sessions (user_id, started_at desc);

-- Every message, click, command, generated response, and error is an event.
create table if not exists public.session_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.bot_sessions(id) on delete cascade,
  user_id bigint not null,
  event_type text not null,
  endpoint text,
  update_kind text,
  handler text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists session_events_session_created_idx
  on public.session_events (session_id, created_at);

create index if not exists session_events_user_created_idx
  on public.session_events (user_id, created_at desc);

alter table public.bot_sessions disable row level security;
alter table public.session_events disable row level security;

drop policy if exists bot_sessions_service_role_access on public.bot_sessions;
create policy bot_sessions_service_role_access
  on public.bot_sessions
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists session_events_service_role_access on public.session_events;
create policy session_events_service_role_access
  on public.session_events
  for all
  to service_role
  using (true)
  with check (true);

-- Permission model:
-- - service_role: full privileges for writes
-- - anon (fallback): allow inserts so accidental anon-key usage does not fully break writes

-- Clear restrictive defaults for public tables (leave policy logic intact)
revoke all on table public.bot_sessions from anon, authenticated, service_role;
revoke all on table public.session_events from anon, authenticated, service_role;

-- service_role grants (expected production key)
grant all on table public.bot_sessions to service_role;
grant all on table public.session_events to service_role;
grant usage, select on sequence public.session_events_id_seq to service_role;

-- anon fallback grants (only used if SUPABASE_SERVICE_ROLE_KEY is missing)
grant select, insert, update on table public.bot_sessions to anon;
grant select, insert, update on table public.session_events to anon;
grant usage, select on sequence public.session_events_id_seq to anon;

-- anon RLS policies (so inserts don't fail if anon key is used)
drop policy if exists bot_sessions_anon_access on public.bot_sessions;
create policy bot_sessions_anon_access
  on public.bot_sessions
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists session_events_anon_access on public.session_events;
create policy session_events_anon_access
  on public.session_events
  for all
  to anon
  using (true)
  with check (true);


-- Interactions table — flat table for logging every user action.
create table public.interactions (
  id bigserial primary key,
  user_id bigint not null,
  username text,
  first_name text,
  action_type text,  -- 'start','click','message','response','error'
  input text,
  response text,
  metadata jsonb,
  created_at timestamptz default now()
);
alter table public.interactions disable row level security;
grant all on table public.interactions to service_role;

-- Remove the previous split storage model after the new tables exist.
drop table if exists public.user_history cascade;
drop table if exists public.user_events cascade;
drop table if exists public.user_data cascade;

commit;
