begin;

create table if not exists public.user_data (
  user_id bigint primary key,
  preferences jsonb default '{}'::jsonb,
  current_feature text,
  last_interaction double precision default 0
);

create table if not exists public.user_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_data(user_id) on delete cascade,
  feature text not null,
  input_data text,
  output_summary text,
  timestamp double precision default 0
);

create index if not exists user_history_user_id_timestamp_idx
  on public.user_history (user_id, timestamp desc);

-- Enable RLS
alter table public.user_data enable row level security;
alter table public.user_history enable row level security;

-- Create policies for service role access
drop policy if exists user_data_backend_access on public.user_data;
create policy user_data_backend_access
  on public.user_data
  for all
  to anon, authenticated, service_role
  using (true)
  with check (true);

drop policy if exists user_history_backend_access on public.user_history;
create policy user_history_backend_access
  on public.user_history
  for all
  to anon, authenticated, service_role
  using (true)
  with check (true);

commit;
